### ISSUE TITLE
Error during installation of materials from RU_RNASEQ page

### ISSUE THREAD

**Issue by hchetia** [RockefellerUniversity/RU_RNAseq#4]
**Command used-** install.packages('BiocManager')
BiocManager::install('RockefellerUniversity/RU_RNAseq',subdir='rnaseq')

**ERROR reported:**

Error: package or namespace load failed for ‘data.table’ in library.dynam(lib, package, package.lib):
 shared object ‘datatable.so’ not found
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/data.table’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/data.table’
Error: Failed to install 'rnaseq' from GitHub:
  (converted from warning) installation of package ‘data.table’ had non-zero exit status

**Comment by matthew-paul-2006** [comment]
I can see from the Version information in the path that you are running R 3.6. We have built the courses in R 4.0 and recommend upgrading. 

You can also install the packages separately by following the instructions under "From CRAN and Bioconductor"

**Comment by hchetia** [comment]
Thanks. That worked.
