### ISSUE TITLE
Error while creating DESeq2 object

### ISSUE THREAD

**Issue by aninditaces** [RockefellerUniversity/RU_RNAseq#9]
While trying to create a DESeq2 object, I am encountering the following error:
Error in rowSums(assay(se) == assay(se)[, 1]) : 
  could not find symbol "..." in environment of the generic function

I tried using the practice dataset as well (from RU_RNAseq-master/r_course/data/GeneCounts.RData) and encountered the same error. 

Could you please help me understand what's going on here? Thanks!

**Comment by matthew-paul-2006** [comment]
So I do not recognize this error. Looking around a little bit at similar errors online it might be an issue relating to the version R and the packages. Could you type sessionInfo() into R and post the response. 

If possible could you also post the code that triggers the error so I know exactly where you are.

**Comment by aninditaces** [comment]
I figured out that my R was acting funny. I am using R 4.1.2.

Thanks.

**Comment by matthew-paul-2006** [comment]
I am glad that you were able to fix it.
